export enum RouteName {
  LOGIN = "Login",
  ABOUT = "About",
  NOT_FOUND = "NotFound",
  SHOP_LIVES = "ShopLives",
  NEW_REGISTATION = "NewRegistation",
  YOUR_WORK = "YourWork",
  USERS = "Users",
  PROFILE = "Profile",
  TASKS = "Tasks",
  LOGIN_PAGE = "LoginPage",
  PROJECTS = "Projects",
  DAYOFF = "Dayoff",
  FORGOT = "Forgot",
  ABSENCE = "Absence",
  ISSUES = "Issues",
  ISSUE = "Issue",
  YOUR_WORK_V2 = "YourworkV2",
}
